{
  "formatVersion": "1.1",
  "component": {
    "group": "Plugins",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rkdp3npoyrbf3ekjbp6bevrbxu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ClassCoverPlugin-1.0.0.jar",
          "url": "ClassCoverPlugin-1.0.0.jar",
          "size": 38382,
          "sha512": "e106f55d522572d910c070d5ab906914f997e260d7a7c771cf577f736af4a29db195e95569021f2416ef482cc5bcc23d276ea3f657d6b9b04bde97b1cf6d638d",
          "sha256": "53c08142754fd86a21449149f07fba4d6f9e50f520461a9fb5cc76a6fb1b2eee",
          "sha1": "fc7ced7885d114a6c74ba1bda761547d6112cf04",
          "md5": "8b39e54126ac06b1ecf6a45e4a329025"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.apache.directory.studio",
          "module": "org.apache.commons.codec",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ClassCoverPlugin-1.0.0.jar",
          "url": "ClassCoverPlugin-1.0.0.jar",
          "size": 38382,
          "sha512": "e106f55d522572d910c070d5ab906914f997e260d7a7c771cf577f736af4a29db195e95569021f2416ef482cc5bcc23d276ea3f657d6b9b04bde97b1cf6d638d",
          "sha256": "53c08142754fd86a21449149f07fba4d6f9e50f520461a9fb5cc76a6fb1b2eee",
          "sha1": "fc7ced7885d114a6c74ba1bda761547d6112cf04",
          "md5": "8b39e54126ac06b1ecf6a45e4a329025"
        }
      ]
    }
  ]
}
