{
  "formatVersion": "1.1",
  "component": {
    "group": "Plugins",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dr4g7yijebenxde57cmmlgrici"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ClassCoverPlugin-1.0.0.jar",
          "url": "ClassCoverPlugin-1.0.0.jar",
          "size": 38382,
          "sha512": "1b88ab4b0b094d85a6d793c86609217516a6c3db847f0618af992d648b1d462973cfbe49c44577e1c859e38479cdcd92cf81f814c62726ac8ff53ea9fc981176",
          "sha256": "bcffa157ad57c90bc0fd4954c21dad0fd0d5c8143d167a3ce01ded042ac6f6b8",
          "sha1": "478ea51d7f3634acf13977b7d5641f724a7e5c51",
          "md5": "6d3ebaded0e3da5aff5ff03f5c49a2bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.apache.directory.studio",
          "module": "org.apache.commons.codec",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ClassCoverPlugin-1.0.0.jar",
          "url": "ClassCoverPlugin-1.0.0.jar",
          "size": 38382,
          "sha512": "1b88ab4b0b094d85a6d793c86609217516a6c3db847f0618af992d648b1d462973cfbe49c44577e1c859e38479cdcd92cf81f814c62726ac8ff53ea9fc981176",
          "sha256": "bcffa157ad57c90bc0fd4954c21dad0fd0d5c8143d167a3ce01ded042ac6f6b8",
          "sha1": "478ea51d7f3634acf13977b7d5641f724a7e5c51",
          "md5": "6d3ebaded0e3da5aff5ff03f5c49a2bb"
        }
      ]
    }
  ]
}
