{
  "formatVersion": "1.1",
  "component": {
    "group": "Plugins",
    "module": "plugin_SimplePlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ee2dglyamjfplpsx4qiucwgppq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin_SimplePlugin-unspecified.jar",
          "url": "plugin_SimplePlugin-unspecified.jar",
          "size": 23313,
          "sha512": "953de14abe43326a8917cca6b459502cb148e84a97039b2882fbc6b30d2e49070fae5678e2572a9dd940246c658d7434bba6394f36ff6bffa7d3cd479d1a593a",
          "sha256": "fae33876516a9b4ed27bad58c4de3cbcec497162e47d195b0ffaf1a9cc1d545b",
          "sha1": "1e5cb9be2eaaeecd4a7f6251350dddb331d11c08",
          "md5": "bfd7066856ded079c6fd954cb925c5de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_SimplePlugin-unspecified.jar",
          "url": "plugin_SimplePlugin-unspecified.jar",
          "size": 23313,
          "sha512": "953de14abe43326a8917cca6b459502cb148e84a97039b2882fbc6b30d2e49070fae5678e2572a9dd940246c658d7434bba6394f36ff6bffa7d3cd479d1a593a",
          "sha256": "fae33876516a9b4ed27bad58c4de3cbcec497162e47d195b0ffaf1a9cc1d545b",
          "sha1": "1e5cb9be2eaaeecd4a7f6251350dddb331d11c08",
          "md5": "bfd7066856ded079c6fd954cb925c5de"
        }
      ]
    }
  ]
}
