{
  "formatVersion": "1.1",
  "component": {
    "group": "Plugins",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "woj5ou5xtfaqnmkx3e63acmgiq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SimplePlugin-1.0.0.jar",
          "url": "SimplePlugin-1.0.0.jar",
          "size": 38370,
          "sha512": "b2a1dfd05e5d71ecc397d9671874686bbccbb2c647cd33162917dd8f4a3325ac2942ade082bda620d93e99d31b63158010a700c47733729743d41d89a0580dc3",
          "sha256": "981c9bc024bcce1876965b4df08aee4d4b2b10a793f3ddf7483c2690a23ca3fa",
          "sha1": "3586b245f1d75e00b729325f362867d19176f7b9",
          "md5": "99b3c822ec5e55d9a55db9ddb9c1ea38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.apache.directory.studio",
          "module": "org.apache.commons.codec",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "SimplePlugin-1.0.0.jar",
          "url": "SimplePlugin-1.0.0.jar",
          "size": 38370,
          "sha512": "b2a1dfd05e5d71ecc397d9671874686bbccbb2c647cd33162917dd8f4a3325ac2942ade082bda620d93e99d31b63158010a700c47733729743d41d89a0580dc3",
          "sha256": "981c9bc024bcce1876965b4df08aee4d4b2b10a793f3ddf7483c2690a23ca3fa",
          "sha1": "3586b245f1d75e00b729325f362867d19176f7b9",
          "md5": "99b3c822ec5e55d9a55db9ddb9c1ea38"
        }
      ]
    }
  ]
}
