{
  "formatVersion": "1.1",
  "component": {
    "group": "Plugins",
    "module": "plugin_ClassCoverPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2ynhxrhwpvecpmgruvywdprcsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin_ClassCoverPlugin-unspecified.jar",
          "url": "plugin_ClassCoverPlugin-unspecified.jar",
          "size": 16827,
          "sha512": "d7e4230ec6538eb090f4dfb7baa4b3b43a4830d430d68fdea497095b7bb96d4b82373a940ca1b46da980a4ba8eb2479733faaf35a8119d99a7dc2e87a0624dab",
          "sha256": "74938113de59c876373f7ca42315efae7e8a49aeb31097379622d740eba6dbad",
          "sha1": "e971f17a2987e73bb799aa1c6b879c1746d5df63",
          "md5": "581760a1487edd734acd6ec3f993d75c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.apache.directory.studio",
          "module": "org.apache.commons.codec",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_ClassCoverPlugin-unspecified.jar",
          "url": "plugin_ClassCoverPlugin-unspecified.jar",
          "size": 16827,
          "sha512": "d7e4230ec6538eb090f4dfb7baa4b3b43a4830d430d68fdea497095b7bb96d4b82373a940ca1b46da980a4ba8eb2479733faaf35a8119d99a7dc2e87a0624dab",
          "sha256": "74938113de59c876373f7ca42315efae7e8a49aeb31097379622d740eba6dbad",
          "sha1": "e971f17a2987e73bb799aa1c6b879c1746d5df63",
          "md5": "581760a1487edd734acd6ec3f993d75c"
        }
      ]
    }
  ]
}
