{
  "formatVersion": "1.1",
  "component": {
    "group": "Plugins",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6thsmghtcveurjdqodq7kh6nu4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-unspecified.jar",
          "url": "plugin-unspecified.jar",
          "size": 38382,
          "sha512": "d4e7933c5e357b9ffdf75665c87313475423cb6ef5209109631d4dcba90dab1d391226b45b09941077eadb7978dc36438537463ebfe57e14c5e4e9bf1961390b",
          "sha256": "b2372de24b6d096a63470e7c291c5bb1005371000e92637cfb3dbd79d7ee33f9",
          "sha1": "969e44487d22bcd2a38c84e03c6c374b8150a6de",
          "md5": "02b0e451b6707d7933bb4a76b2fb6234"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.apache.directory.studio",
          "module": "org.apache.commons.codec",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-unspecified.jar",
          "url": "plugin-unspecified.jar",
          "size": 38382,
          "sha512": "d4e7933c5e357b9ffdf75665c87313475423cb6ef5209109631d4dcba90dab1d391226b45b09941077eadb7978dc36438537463ebfe57e14c5e4e9bf1961390b",
          "sha256": "b2372de24b6d096a63470e7c291c5bb1005371000e92637cfb3dbd79d7ee33f9",
          "sha1": "969e44487d22bcd2a38c84e03c6c374b8150a6de",
          "md5": "02b0e451b6707d7933bb4a76b2fb6234"
        }
      ]
    }
  ]
}
